### ISSUE TITLE
Add/Edit Users: 'Enter Institute Name' should be replaced with 'Enter Organization Name' on 'Organization Name' field.

### ISSUE THREAD

**Issue by neelesh1991** [neelesh1991/Emmersive-ELMS#10]
Add/Edit Users: 'Enter Institute Name' should be replaced with 'Enter Organization Name' on 'Organization Name' field.

Steps:
1. Open Manage Users Page.
2. Click on "Add Users" button. Pop-up page will appeared.

![8](https://user-images.githubusercontent.com/58292920/70137281-9b60f080-16b3-11ea-8baf-fde002344ed9.png)

**Comment by nilesh2019** [comment]
'Enter Institute Name'  replaced with 'Enter Organization Name'
