### ISSUE TITLE
Spell wrong: Manage Assessment master: "Successfully" spell is wrong, please correct it.

### ISSUE THREAD

**Issue by neelesh1991** [neelesh1991/Emmersive-ELMS#33]
Spell wrong: Manage Assessment master: "Successfully" spell is wrong, please correct it.

![22](https://user-images.githubusercontent.com/58292920/70537018-d4063b80-1b85-11ea-81a9-8b05c7583f7f.png)

**Comment by nilesh2019** [comment]
Changed text of Successfullyy to Successfully.
