### ISSUE TITLE
Add/Edit Section: Green tick should be align properly.

### ISSUE THREAD

**Issue by neelesh1991** [neelesh1991/Emmersive-ELMS#37]
Add/Edit Section: Green tick should be align properly.

![26](https://user-images.githubusercontent.com/58292920/70617270-3a4a9700-1c36-11ea-93dc-439485d7a576.png)

**Comment by nilesh2019** [comment]
![OBINCO   Admin Panel](https://user-images.githubusercontent.com/58296306/70993205-82affc00-20f1-11ea-90da-b25c1223fe32.png)
