### ISSUE TITLE
Manage Assessment Sections: Section name column values should be left align for maintaining the consistency.

### ISSUE THREAD

**Issue by neelesh1991** [neelesh1991/Emmersive-ELMS#38]
Manage Assessment Sections: Section name column values should be left align for maintaining the consistency.

Please find attached screenshot:

![27](https://user-images.githubusercontent.com/58292920/70617688-31a69080-1c37-11ea-8938-9193f8f9e2d6.png)

**Comment by nilesh2019** [comment]
![OBINCO   Admin Panel](https://user-images.githubusercontent.com/58296306/70971090-27b4df80-20c6-11ea-9608-7aed819481cd.png)
