### ISSUE TITLE
Manage Assessment Section: Quiz Sections Details: Section Name value should be align properly.

### ISSUE THREAD

**Issue by neelesh1991** [neelesh1991/Emmersive-ELMS#39]
Manage Assessment Section: Quiz Sections Details: Section Name value should be align properly.

Please find attached screenshot:

![28](https://user-images.githubusercontent.com/58292920/70618114-16885080-1c38-11ea-9b23-c657b6258a21.png)

**Comment by nilesh2019** [comment]
Aligned Section name properly.
